### ISSUE TITLE
username isn't mention in the environment variables in docker-compose.yml

### ISSUE THREAD

**Issue by viveksahu26** [iamvickyav/SpringBoot_Docker_MySQL_RabbitMQ#1]
On opening the application it is asking for Username and Password.. Paasword is mentioned but username isn't mention in the docker-compose.yml

**Comment by iamvickyav** [comment]
Hi @viveksahu26 , thanks for asking.. 

I guess you are asking about the MYSQL User name.. 

MYSQL_ROOT_PASSWORD is the password we set for the **MySQL root user**

Pls refer https://hub.docker.com/_/mysql for the same

After you run docker-compose up command, try connecting to the DB using MySQL workbench with user name as root & password mentioned in docker-compose.yaml file. I tried & its working. 

Closing this issue..
